### ISSUE TITLE
What exactly makes the closure-less generativity trick work?

### ISSUE THREAD

**Issue by CAD97** [CAD97/generativity#1]
```rust
// revision 3
let tag = unsafe { $crate::Id::new() };
let $name = unsafe { $crate::Guard::new(tag) };
let _guard = {
    #[allow(non_camel_case_types)]
    struct make_guard<'id> {
        _id: $crate::Id<'id>,
    }
    impl<'id> $crate::core_::ops::Drop for make_guard<'id> {
        #[inline(always)]
        fn drop(&mut self) {}
    }
    fn make_guard<'id>(id: &'id $crate::Id<'id>) -> make_guard<'id> {
        make_guard { _id: *id }
    }
    make_guard(&tag)
};
```

This creates an invariant lifetime `'id` here, and ties it to the borrow of `tag`, which must live until the end of the current scope. i.e., we must have `&'id Id<'id>` at the `make_guard!` location, and have `&'id Id<'id>` at the drop location for `make_guard!`, where `'id` is an invariant lifetime.

This lifetime is additionally not unifyable with any other lifetime produced with `make_guard!` (thus unique). This is because any other `make_guard!` called _before_ ours has a lifetime that must live longer than ours (to drop _after_ ours), and any other `make_guard!` called _after_ ours has a lifetime that must live shorter than ours (to drop _before_ ours).

If an `Id<'id>` or `Guard<'id>` can be tied to a lifetime other than one generated by `make_guard!`, we lose. But so long as all `'id` trusted unique liftetimes come from `make_guard!`, they are indeed unique.

cc @RalfJung; is my reasoning correct?

-----

<details><summary>Previous versions</summary>

```rust
// revision 2
let tag = unsafe { $crate::Id::new() };
let $name = unsafe { $crate::Guard::new(tag) };
let _guard = {
    #[allow(non_camel_case_types)]
    struct make_guard<'id>(&'id $crate::Id<'id>);
    impl<'id> ::core::ops::Drop for make_guard<'id> {
        fn drop(&mut self) {}
    }
    make_guard(&tag)
};
```

```rust
// revision 1
let tag = unsafe { $crate::Id::new() };
let _guard;
let $name = unsafe { $crate::Guard::new(tag) };
if false { // mir opt
    #[allow(non_camel_case_types)]
    struct make_guard<'id>(&'id $crate::Id<'id>);
    impl<'id> ::core::ops::Drop for make_guard<'id> {
        fn drop(&mut self) {}
    }
    _guard = make_guard(&tag);
}
```

**Comment by CAD97** [comment]
The README contains this information now, so I will close this issue. I'm going to pin it, though: this is the place to discuss the soundness of this API.

**Comment by RalfJung** [comment]
> is my reasoning correct?

I have no idea.^^ This is based on a whole bunch of assumptions about implementation details of the borrow checker. The fact that you are using a new unique type per macro invocation makes me suspicious, are lifetimes not enough? Why are there *three* local variables? And why is there a conditional? This is all very weird.

This might work, or not, and it might just work for no good reason (because of some random choice in the compiler). I cannot tell. I don't see any way to formally argue that this is correct.

**Comment by CAD97** [comment]
I can actually answer all these questions!

### new unique type per macro invocation

This was to avoid adding a new type to the public API, and for slightly more useful errors (as it refers to "the lifetime of `tag` required by the `Drop` impl of `make_guard`, defined in this macro invocation, to live to the end of the scope).

I initially did this with another public `generativity` type but removed it for cleanliness of the public API and said marginally better error.

### _three_ local variables

- `$name` is the owned `#[unique] 'id` type which we give to the calling context and don't want to restrict in any extra fashion.
- `tag` is a location in the calling context to which we bind the `'id` lifetime to enforce that it cannot be unified with another guarded lifetime.
- `_guard` is an `impl Drop` holder of `&'id tag` that enforces that `'id` has a unique end timing.

`tag` and `_guard` together guarantee that `'id` lives to a drop point that is different from the drop point of any other `make_guard!` created lifetime, so unifying the two lifetimes would be incorrect. It's also _very_ important that neither `tag` nor `_guard` are leaked from our protected hygiene, as if they could be manipulated, the drop timing could potentially be changed.

### conditional

This is a (probably unnecessary) micro-optimization. (It's not required for safety.) This `if false` makes it trivial for MIR to prove that the drop will never actually run and optimize it and the `_guard: make_guard` place out, but still require the lifetime effects as if it were there.

### semiformal argument

My semiformal argument is based on the end timing of `'id`.

- `'id` is invariant due to the invariance in `tag: generativity::Tag<'id>`.
- `$name: Guard<'id>` has the same lifetime because it is created from `tag`.
- `'id` is named when we create `_guard: make_guard(&'id generativity::Tag<'id>)`.
- The end point of the `'id` lifetime region is tied to be between the drop timing of `tag` and `_guard` by the `Drop` impl of `_guard: make_guard(&'id tag)`.
- Therefore, no lifetime can unify with `'id` unless it can end in the same region.
- All lifetimes created with `make_guard!` are protected in this manner.
- All lifetimes created with `make_guard!` are confined to end at different drop timings.
- Therefore, all lifetimes created with `make_guard!` are mutually ununifyable.
- It is unsafe to create a `generativity::Guard<'_>` without using `make_guard!`.
- Therefore, it is impossible to safely create a `generativity::Guard<'_>` that will unify lifetimes with `'id`.
- Thus, the lifetime created by `make_guard!` and handed out as `generativity::Guard<'id>` is guaranteed unique
  - (while the type exists, of course the caller can convert it into a `generativity::Tag<'id>` and duplicate it to write unsafe code relying on being able to track the invariant lifetime nobody else can produce).

Thus, predicated on the assumption that `Drop` timing will not change, `generativity` is sound.

**Comment by RalfJung** [comment]
@CAD97 thanks a lot! I think most of this would be worth adding to the README. :)

I am not familiar enough with the borrow checker implementation to check your proof sketch. But the ingredients you mention make sense. Whether they are sufficient... well, with Polonius we will hopefully have a formal model of the borrow checker and then proving this would be a fun project. ;)

> This was to avoid adding a new type to the public API, and for slightly more useful errors (as it refers to "the lifetime of tag required by the Drop impl of make_guard, defined in this macro invocation, to live to the end of the scope).

So the new unique type is not required for soundness, then?

> This if false makes it trivial for MIR to prove that the drop will never actually run and optimize it and the _guard: make_guard place out, but still require the lifetime effects as if it were there.

Interesting; to what extend NLL should even check dead code was subject of discussion if I recall correctly.

@matthewjasper so here we have some code that actually heavily relies on dead code affecting borrow checking. I do not know the exact current status of this, just that there was some effort with NLL to make this happen at least most of the time?

**Comment by CAD97** [comment]
> So the new unique type is not required for soundness, then?

That is correct. The `make_guard` type could just as well be a singular type exposed by the crate.

> code that actually heavily relies on dead code affecting borrow checking

To be clear, I'd be happy to remove the `if false` around the block, especially if it makes the correctness less questionable. It's unnecessary and just there as a probably unnecessary micro-optimization hint. (However, I do think it's more proper for all not-cfg'd-out code to impact the borrow liveness analysis, even if it's unreachable.)

**Comment by RalfJung** [comment]
> However, I do think it's more proper for all not-cfg'd-out code to impact the borrow liveness analysis, even if it's unreachable.

Fair. The only problem is, with a CFG-based borrow checker, that's actually not trivial to achieve (from what I understood).

**Comment by CAD97** [comment]
Naively, I'd expect an `if false` block to still be represented in the CFG as two edges, just where one is trivially provable to be never taken. The borrow checker would continue to assume every edge could be taken.

That said, I went ahead and removed the `if false` in #9. I'll push a patch version later today.
