### ISSUE TITLE
warning: zero-sized fields in repr(transparent) cannot contain external non-exhaustive types

### ISSUE THREAD

**Issue by SoniEx2** [CAD97/generativity#13]
This seems like a problem for being able to use generativity:

```
warning: zero-sized fields in repr(transparent) cannot contain external non-exhaustive types
 --> src/lib.rs:6:39
  |
6 | pub struct BOption<'id, T>(Option<T>, Id<'id>);
  |                                       ^^^^^^^
  |
  = note: `#[warn(repr_transparent_external_private_fields)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #78586 <https://github.com/rust-lang/rust/issues/78586>
  = note: this struct contains `Id<'id>`, which contains private fields, and makes it not a breaking change to become non-zero-sized in the future.
```

But maybe we're using it wrong?

**Comment by CAD97** [comment]
(Sorry it took so long to reply; life happened)

`Id` is guaranteed by the library to be a 1-ZST, and this is an intended use pattern. The type is currently default repr, but I'll mark it as `#[repr(transparent)]`. IIUC that won't prevent the warning currently, but that's considered a bug in the implementation of the lint, and such types should be accepted.

**Comment by CAD97** [comment]
There's no workaround possible that can convince `warn(repr_transparent_external_private_fields)` to not consider `Id` as potentially non-1ZST. This is certainly a bug that e.g. `struct Trans(usize, Cell<()>)` is warned, since `Cell` is guaranteed by its own `repr(transparent)` to transparently be its wrapped type, which is in this case a 1ZST.

It's still better form for the relevant types to be marked `#[repr(transparent)]`, so I've now published v1.1.0 which adds `#[repr(transparent)]` and improves the docs a bit. I'm going to close this as I've addressed it the best I can, but keep it pinned until it's resolved upstream.

**Comment by CAD97** [comment]
See also https://github.com/rust-lang/rust/issues/78586

**Comment by RalfJung** [comment]
>  that's considered a bug in the implementation of the lint

This claim is based on -- what? You may consider this a bug, but nothing in https://github.com/rust-lang/rust/issues/78586 indicates that it is considered a bug in rustc. If you don't file issues or give feedback on the tracking issue you can't expect people to magically know that there's a behavior that you consider a bug here. The tracking issue was open for literal years and no such issue was filed by anyone as far as I can tell.

**Comment by CAD97** [comment]
I don't recall exactly what I was thinking three years ago, but I vaguely recall having some reason to believe "we want some way to guarantee 1ZST types that aren't publicly constructible" was a known limitation at that point.

If I had run into this again in the interim, I would've said something at that point. I only just now pushed and update to this crate and looked through things again.

It's not *necessary* for these types to be known 1ZST, it's just a significant boost to the utility.

**Comment by CAD97** [comment]
As for why *I* consider that a bug — the lint says that `Cell<()>` isn't guaranteed to be 1ZST, but it definitely is.

**Comment by RalfJung** [comment]
> the lint says that Cell<()> isn't guaranteed to be 1ZST, but it definitely is.

That's an interesting point, which has to do with `#[rustc_pub_transparent]`.

Let's move this to some suitable rustc issue. Do you know if there already is one?
